### ISSUE TITLE
Error on npm run benchmark

### ISSUE THREAD

**Issue by diasdavid** [ipfs/ipfs-performance-profiling#1]
Got a:

```
files-add-1MB-file started
RUNNING files-add-1MB-file-go
/Users/koruza/code/ipfs-performance-profiling/src/run.js:105
                throw err
                ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)
```

**Comment by diasdavid** [comment]
Ok, managed to get a success.

```
all finished

Results:

files-add-small-file:
  go:
    mean: 0.0051804018378787875, variance: 0.0000020685669743319283, deviation: 0.001438251359927022, moe: 0.0015095977671541073, rme: 29.140553462783892, sem: 0.000587163658947533
  js-core:
    mean: 0.0007622843761093726, variance: 6.295453757216796e-8, deviation: 0.0002509074282921252, moe: 0.0000808478971524892, rme: 10.606002128120377, sem: 0.00004124892711861694
  js-http:
    mean: 0.012505632104554866, variance: 0.0001588189223922244, deviation: 0.012602337973258153, moe: 0.005449993151236286, rme: 43.580309301208864, sem: 0.002627769118243147
files-add-1MB-file:
  go:
    mean: 0.01047937522222222, variance: 0.0000011576243778583404, deviation: 0.0010759295413075803, moe: 0.0011293024838547555, rme: 10.776429509461535, sem: 0.000439246395898388
  js-core:
    mean: 0.010206947995366793, variance: 0.000003960093655335094, deviation: 0.00198999840586245, moe: 0.000641221296419602, rme: 6.282204011528907, sem: 0.0003271537226630622
  js-http:
    mean: 0.027845456017543856, variance: 0.00004849047048774761, deviation: 0.006963509925874136, moe: 0.0033564288926546068, rme: 12.053775993253296, sem: 0.0015975387399593559
files-add-100MB-file:
  go:
    mean: 0.6125973525, variance: 0.0029665012510167346, deviation: 0.054465596949053396, moe: 0.0571674366747538, rme: 9.331975798043265, sem: 0.022235486843544844
  js-core:
    mean: 0.9354624237777779, variance: 0.003997317831109014, deviation: 0.06322434524065089, moe: 0.04859844670831365, rme: 5.195125477307078, sem: 0.02107478174688363
  js-http:
    mean: 1.6324412668571426, variance: 0.010432273037259951, deviation: 0.10213849929022822, moe: 0.09446575977037731, rme: 5.786778470275228, sem: 0.038604724058184436
```

Let's round this values microseconds `μs` and make a table that looks like this:

|                      |           | go-ipfs | js-ipfs core | js-ipfs http |
|----------------------|-----------|---------|--------------|--------------|
| files-add-small-file | mean      |         |              |              |
|                      | variance  |         |              |              |
|                      | deviation |         |              |              |
|                      | moe       |         |              |              |
|                      | rme       |         |              |              |
|                      | sme       |         |              |              |
| files-add-1MB-file   |           |         |              |              |
| ...                  |           |         |              |              |

So it is easy to assess how it performed at first glance. Do we actually need `moe, rme and sme` displayed?
